runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
  secure: always
- url: /stylesheets
  static_dir: stylesheets

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
