runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: main.app
  secure: always
<<<<<<< HEAD
=======

>>>>>>> d3424229c8028ebad89e46369e0beb57130c1135

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
